# Generated by Django 3.2.4 on 2021-07-02 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='exchange',
            name='ask_price',
            field=models.IntegerField(null=True, verbose_name='Ask Price'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='bid_price',
            field=models.IntegerField(null=True, verbose_name='Bid price'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='exchange_rate',
            field=models.IntegerField(null=True, verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='fetched',
            field=models.DateTimeField(null=True, verbose_name='Fetched Timestamp'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='to_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='To', to='alpha.currency'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='from_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='From', to='alpha.currency'),
        ),
    ]
