# Generated by Django 3.2.4 on 2021-07-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    def create_currency(apps, schema_editor):
        Currency = apps.get_model('alpha', 'Currency')
        Currency.objects.create(code='BTC', name='Bitcoin')
        Currency.objects.create(code='USD', name='United States Dollar')


    dependencies = [
        ('alpha', '0002_auto_20210702_0753'),
    ]

    operations = [
        migrations.RunPython(create_currency)
    ]
