# Generated by Django 3.2.4 on 2021-07-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0003_auto_20210702_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='ask_price',
            field=models.FloatField(null=True, verbose_name='Ask Price'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='bid_price',
            field=models.FloatField(null=True, verbose_name='Bid price'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_rate',
            field=models.FloatField(null=True, verbose_name='Exchange Rate'),
        ),
    ]
