# Generated by Django 3.2.4 on 2021-07-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0004_auto_20210702_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='fetched',
            field=models.DateTimeField(null=True, verbose_name='Fetched Timestamp(UTC)'),
        ),
    ]
